cargo-features = ["per-package-target"]

[workspace]

[package]
name = "handler"
version = "0.1.0"
edition = "2021"
default-target = "wasm32-wasi"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.4.0"